DropGoldenApple: false
BadCommand: '&4You can't use that in here. If you want to leave, use &6/leave'
JoinMessage: '&aYou joined KitPvP!'
LeaveMessage: '&6You left KitPvP!'
SignStart: '[KitPvP]'
moneyperkill: 5
ImmuneTimeInSeconds: 0
CobwebDestroyTimeInSeconds: 30
currencyname: Pounds
CommandWhitelist:
  - money
EnableAutoUpdater: true