name: KitPvP
version: 1.4
main: me.oliver276.kitpvp.Main
description: KitPvP

commands:
    kitpvp:
        usage: /<command>
        description: Basic command for KitPvP.
        aliases: [DeathArena]
permissions:
    kitpvp.join:
        default: true
    kitpvp.setinv:
        default: op
    kitpvp.setspawn:
        default: op
